config/routes.rb
Rails.application.routes.draw do
  resources :announcements
  devise_for :users
  resources :proposals
  resources :reviews
  resources :comments

  root :to => 'landing_page#index'
  post '/' => 'landing_page#index', as:'home_page'
  get '/edit' => 'users#edit_profile', as: 'edit_profile'
  patch '/edit/:id' => 'users#edited_profile', as: 'user'
  get '/proposals' => 'proposals#index', as:'proposals_page'
  get '/proposals/:id/veto' => 'proposals#veto', as: 'veto'
  post '/proposals/:id/veto' => 'proposals#vetoed', as: 'vetoed'
  get '/proposals/:id/assign' => 'proposals#assign', as: 'assign_proposal'
  post '/proposals/:id/assignhead/:memberid' => 'proposals#assign_head_to_proposal', as: 'assign_head_to_proposal'
  post '/proposals/:id/assignmember/:memberid' => 'proposals#assign_member_to_proposal', as: 'assign_member_to_proposal'
  post '/proposals/:id/removehead/:memberid' => 'proposals#remove_head_from_proposal', as: 'remove_head_from_proposal'
  post '/proposals/:id/removemember/:memberid' => 'proposals#remove_member_from_proposal', as: 'remove_member_from_proposal'
  get '/proposals/:id/editsubmissionperiod' => 'proposals#edit_submission_period', as: 'edit_submission_period'
  post '/proposals/:id/editsubmissionperiod' => 'proposals#edit_period', as: 'edit_period'
  get '/under_construction', to: "landing_page#under_construction", as: "under_construction"
  get '/proposals/:id/withdraw' => 'proposals#withdraw', as: 'withdraw_proposal'
  get 'proposals/:id/reviews' => 'reviews#index', as: 'reviews_page'
  post 'proposals/:id/reviews' => 'reviews#add_comment', as:"add_comment"
  post 'proposals/:id/uphold' => 'proposals#uphold', as:"uphold"
  get '/assign' => 'users#index', as: 'assign_account'
  get '/user/:id' => 'users#view', as: 'view_user'
  get '/remove/:id' => 'users#edit', as: 'edit_account'
  post '/add/:id/researcher' => 'users#add_researcher', as: 'add_researcher'
  post '/add/:id/dean' => 'users#add_dean', as: 'add_dean'
  post '/add/:id/member' => 'users#add_committee_member', as: 'add_committee_member'
  post '/add/:id/head' => 'users#add_committee_head', as: 'add_committee_head'
  post '/add/:id/admin' => 'users#add_admin', as: 'add_admin'

  post '/remove/:id/researcher' => 'users#remove_researcher', as: 'remove_researcher'
  post '/remove/:id/dean' => 'users#remove_dean', as: 'remove_dean'
  post '/remove/:id/member' => 'users#remove_committee_member', as: 'remove_committee_member'
  post '/remove/:id/head' => 'users#remove_committee_head', as: 'remove_committee_head'
  post '/remove/:id/admin' => 'users#remove_admin', as: 'remove_admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # before_create :set_user_type
  after_initialize :set_defaults
  after_save :create_types  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :admin, dependent: :destroy
  has_one :committee_member, dependent: :destroy
  has_one :researcher, dependent: :destroy
  has_one :dean, dependent: :destroy
  has_one :committee_head, dependent: :destroy
  validates :first_name, :last_name, :rank, :department, :contact_number, presence: true

  def set_defaults
  	self.first_name ||= ''
  	self.last_name ||= ''
  	self.department ||= ''
  	self.rank ||= ''
  	self.contact_number ||= ''
    self.curr_type = 'Researcher' if self.curr_type.nil?
  end

  def create_types
    self.create_committee_member!(user_id: self.id) if self.committee_member.nil?
    self.create_admin!(user_id: self.id) if self.admin.nil?
    self.create_dean!(user_id: self.id) if self.dean.nil?
    self.create_committee_head!(user_id: self.id) if self.committee_head.nil?
    self.create_researcher!(user_id: self.id) if self.researcher.nil?
  end

  def full_name
    return self.last_name + ', ' + self.first_name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def view
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def edit_profile
		@user = current_user
	end

	def edited_profile
		@user = User.find(params[:id])
		if @user.update_with_password(user_params)
      # Sign in the user by passing validation in case their password changed
      		bypass_sign_in(@user)
      		redirect_to home_page_path

      	else
      		render "edit_profile"
    	end


	end

	def add_dean
		@user = User.find(params[:id])
		@user.dean.activated = true
		@user.dean.save!
		@user.save!
		redirect_to edit_account_path
	end

	def add_committee_head
		@user = User.find(params[:id])
		@user.committee_head.activated = true
		@user.committee_head.save!
		@user.save!
		redirect_to edit_account_path
	end

	def add_committee_member
		@user = User.find(params[:id])
		@user.committee_member.activated = true
		@user.committee_member.save!
		@user.save!
		redirect_to edit_account_path
	end

	def add_researcher
		@user = User.find(params[:id])
		@user.researcher.activated = true
		@user.researcher.save!
		@user.save!
		redirect_to edit_account_path
	end

	def add_admin
		@user = User.find(params[:id])
		@user.admin.activated = true
		@user.admin.save!
		@user.save!
		redirect_to edit_account_path
	end

	def remove_dean
		@user = User.find(params[:id])
		@user.dean.activated = false
		@user.dean.save!
		@user.save!
		redirect_to edit_account_path
	end

	def remove_committee_head
		@user = User.find(params[:id])
		@user.committee_head.activated = false
		@user.committee_head.save!
		@user.save!
		redirect_to edit_account_path
	end

	def remove_committee_member
		@user = User.find(params[:id])
		@user.committee_member.activated = false
		@user.committee_member.save!
		@user.save!
		redirect_to edit_account_path
	end

	def remove_researcher
		@user = User.find(params[:id])
		@user.researcher.activated = false
		@user.researcher.save!
		@user.save!
		puts "++++"
		puts "++++"
		redirect_to edit_account_path
	end

	def remove_admin
		@user = User.find(params[:id])
		@user.admin.activated = false
		@user.admin.save!
		@user.save!
		redirect_to edit_account_path
	end

	def user_params
		params.require(:user).permit(:first_name, :last_name, :department, :rank, :contact_number, :email, :password, :password_confirmation, :current_password)
	end
end

app/views/users/edit.html.erb
<h1>Account Privileges: <%= @user.full_name %></h1>
<div class="ui message">
  <div class="header">About Account Privileges</div>
  <p>You can assign any of the following account types to the user:</p>
  <ul class="list">
    <li>Dean - can view proposals and their comments; gives final decisions for proposals</li>
    <li>Researcher - can submit proposals</li>
    <li>Committee Member - can view, vote on, and comment on proposals</li>
    <li>Committee Head - can view, vote on, and comment on proposals; sets submission period</li>
    <li>Admin - can manage announcements, account privileges, and review committee assignments</li>
  </ul>
</div>

<table class = "ui celled padded table">
  <tr>
    <th>
      Dean
    </th>
    <% if @user.dean.activated == true %>
      <td>
        <%= link_to "Remove Privilege", remove_dean_path(:id => @user.id), :method => :post %>
      </td>
    <% else %>
      <td>
        <%= link_to "Add Privilege", add_dean_path(:id => @user.id), :method => :post %>
      </td>
    <% end %>
  </tr>
  <tr>
    <th>
      Researcher
    </th>
    <% if @user.researcher.activated == true %>
      <td>
        <%= link_to "Remove Privilege", remove_researcher_path(:id => @user.id), :method => :post %>
      </td>
    <% else %>
      <td>
        <%= link_to "Add Privilege", add_researcher_path(:id => @user.id), :method => :post %>
      </td>
    <% end %>
  </tr>
  <tr>
    <th>
      Committee Member
    </th>
    <% if @user.committee_member.activated == true %>
      <td>
        <%= link_to "Remove Privilege", remove_committee_member_path(:id => @user.id), :method => :post %>
      </td>
    <% else %>
      <td>
        <%= link_to "Add Privilege", add_committee_member_path(:id => @user.id), :method => :post %>
      </td>
    <% end %>
  </tr>
  <tr>
    <th>
      Committee Head
    </th>
    <% if @user.committee_head.activated == true %>
      <td>
        <%= link_to "Remove Privilege", remove_committee_head_path(:id => @user.id), :method => :post %>
      </td>
    <% else %>
      <td>
        <%= link_to "Add Privilege", add_committee_head_path(:id => @user.id), :method => :post %>
      </td>
    <% end %>
    </tr>
    <tr>
    <th>
      Admin
    </th>
    <% if @user.admin.activated == true %>
      <td>
        <%= link_to "Remove Privilege", remove_admin_path(:id => @user.id), :method => :post %>
      </td>
    <% else %>
      <td>
        <%= link_to "Add Privilege", add_admin_path(:id => @user.id), :method => :post %>
      </td>
    <% end %>
  </tr>
</table>

<br>
<%= link_to 'Back', assign_account_path, :class => "ui primary button" %>

app/views/users/edit_profile.html.erb
<h1>Edit Profile</h1>

<%= form_for @user, html: { multipart: true, class: "ui form" } do |f| %>
  <div class="ui padded segment">
    <div class="field">
      <label>First name</label>
      <%= f.text_field :first_name %>
    </div>
    <div class="field">
      <label>Last name</label>
      <%= f.text_field :last_name %>
    </div>
    <div class="field">
      <label>Department/Institute</label>
      <%= f.text_field :department %>
    </div>
    <div class="field">
      <label>Rank</label>
      <%= f.text_field :rank %>
    </div>
    <div class="field">
      <label>Contact number</label>
      <%= f.text_field :contact_number %>
    </div>
    <div class="field">
      <label>Email</label>
      <%= f.email_field :email %>
    </div>
    <div class="field">
      <label>Password</label>
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <label>Password confirmation</label>
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="field">
      <label>Current password</label><i>(we need your current password to confirm your changes)</i><br>
      <%= f.password_field :current_password %>
    </div>
  </div>
  <%= f.submit "Save", :class => "ui primary button" %>
<% end %>

app/views/users/index.html.erb
<h1>Account Management</h1>
<table class="ui celled padded table">
	<tbody>
    <% @users.each do |user| %>
      <tr>
          <th><%= link_to user.full_name, view_user_path(user.id) %></th>
          <td>
          <% if user.dean.activated == true %>
            <div class="ui label">Dean</div>
          <% end %>
          <% if user.researcher.activated == true %>
            <div class="ui label">Researcher</div>
          <% end %>
          <% if user.committee_member.activated == true %>
            <div class="ui label">Committee Member</div>
          <% end %>
          <% if user.committee_head.activated == true %>
            <div class="ui label">Committee Head</div>
          <% end %>
          <% if user.admin.activated == true %>
            <div class="ui label">Admin</div>
          <% end %>
          </td>
          <td><%= link_to "Edit Privileges", edit_account_path(user.id) %></td>
      </tr>
    <% end %>
	</tbody>
</table>

app/views/users/view.html.erb
<h1>Account Details</h1>

<table class="ui celled padded table">
	<tbody>
		<tr><th>First Name</th><td><%= @user.first_name %></td></tr>
		<tr><th>Last Name</th><td><%= @user.last_name %></td></tr>
		<tr><th>Department</th><td><%= @user.department %></td></tr>
		<tr><th>Rank</th><td><%= @user.rank %></td></tr>
		<tr><th>Contact Number</th><td><%= @user.contact_number %></td></tr>
    <tr><th>Email</th><td><%= @user.email %></td></tr>
	</tbody>
</table>

<br>
<%= link_to 'Back', assign_account_path, :class => "ui primary button" %>