config/routes.rb
Rails.application.routes.draw do
  resources :announcements
  devise_for :users
  resources :proposals
  resources :reviews
  resources :comments

  root :to => 'landing_page#index'
  post '/' => 'landing_page#index', as:'home_page'
  get '/edit' => 'users#edit_profile', as: 'edit_profile'
  patch '/edit/:id' => 'users#edited_profile', as: 'user'
  get '/proposals' => 'proposals#index', as:'proposals_page'
  get '/proposals/:id/veto' => 'proposals#veto', as: 'veto'
  post '/proposals/:id/veto' => 'proposals#vetoed', as: 'vetoed'
  get '/proposals/:id/assign' => 'proposals#assign', as: 'assign_proposal'
  post '/proposals/:id/assignhead/:memberid' => 'proposals#assign_head_to_proposal', as: 'assign_head_to_proposal'
  post '/proposals/:id/assignmember/:memberid' => 'proposals#assign_member_to_proposal', as: 'assign_member_to_proposal'
  post '/proposals/:id/removehead/:memberid' => 'proposals#remove_head_from_proposal', as: 'remove_head_from_proposal'
  post '/proposals/:id/removemember/:memberid' => 'proposals#remove_member_from_proposal', as: 'remove_member_from_proposal'
  get '/proposals/:id/editsubmissionperiod' => 'proposals#edit_submission_period', as: 'edit_submission_period'
  post '/proposals/:id/editsubmissionperiod' => 'proposals#edit_period', as: 'edit_period'
  get '/under_construction', to: "landing_page#under_construction", as: "under_construction"
  get '/proposals/:id/withdraw' => 'proposals#withdraw', as: 'withdraw_proposal'
  get 'proposals/:id/reviews' => 'reviews#index', as: 'reviews_page'
  post 'proposals/:id/reviews' => 'reviews#add_comment', as:"add_comment"
  post 'proposals/:id/uphold' => 'proposals#uphold', as:"uphold"
  get '/assign' => 'users#index', as: 'assign_account'
  get '/user/:id' => 'users#view', as: 'view_user'
  get '/remove/:id' => 'users#edit', as: 'edit_account'
  post '/add/:id/researcher' => 'users#add_researcher', as: 'add_researcher'
  post '/add/:id/dean' => 'users#add_dean', as: 'add_dean'
  post '/add/:id/member' => 'users#add_committee_member', as: 'add_committee_member'
  post '/add/:id/head' => 'users#add_committee_head', as: 'add_committee_head'
  post '/add/:id/admin' => 'users#add_admin', as: 'add_admin'

  post '/remove/:id/researcher' => 'users#remove_researcher', as: 'remove_researcher'
  post '/remove/:id/dean' => 'users#remove_dean', as: 'remove_dean'
  post '/remove/:id/member' => 'users#remove_committee_member', as: 'remove_committee_member'
  post '/remove/:id/head' => 'users#remove_committee_head', as: 'remove_committee_head'
  post '/remove/:id/admin' => 'users#remove_admin', as: 'remove_admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer>
	&copy; University of the Philippines Diliman - College of Engineering 2018
</footer>

app/views/shared/_nav.html.erb
<nav class = "navbar navbar-default navbar-fixed-top">
  <a class = "navbar-brand"><%= link_to image_tag("fria-logo.png", :width => 180), home_page_path %></a>
  <div class = "welcome">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>.
  <% end %>
  </div>
  <% if user_signed_in? %>
    <div class = "welcome-main">
    Hello, <%= "#{current_user.first_name} #{current_user.last_name}"%>.
    <% if current_user.curr_type %>
      Signed in as <%= current_user.curr_type == 'CommitteeMember' ? 'Committee Member' : current_user.curr_type == 'CommitteeHead'? 'Committee Head' : current_user.curr_type %>.
    <% end %>
    </div>
    <div class="menu">
      <%= link_to "HOME", home_page_path %>
       | <%= link_to "EDIT PROFILE", edit_profile_path %>
      <% if can? :index, Proposal %>
        | <%= link_to "PROPOSALS", proposals_page_path %>
      <% end %>
      <% if can? :index, User %>
        | <%= link_to "ACCOUNTS", assign_account_path %>
      <% end %>
      <% if can? :manage, Announcement %>
        | <%= link_to "ANNOUNCEMENTS", announcements_path %>
      <% end %>
      | <%= link_to "LOG OUT", destroy_user_session_path, :method => :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <% else %>
    <div class = "welcome-main">
      <%= link_to "Log in", new_user_session_path %> or
      <%= link_to "Sign Up", new_user_registration_path %>
    </div>
  <!--
    <div class = "welcome-main">
      <%= form_for(@user, :url => session_path(@user), :html => {class: "ui form", id: "login"}) do |f| %>
        <div class="fields">
          <div class="field">
            <%= f.label :email %>
            <%= f.email_field :email, autofocus: true, placeholder: "Email" , required: true%>
          </div>
          <div class="field">
            <%= f.label :password %>
            <%= f.password_field :password, autocomplete: "off", placeholder: "Password", required: true%>
          </div>
          <%= f.submit "Login", class: "ui button", id: "login_button" %>
        </div>
      <% end %>
    </div> -->
  <% end %>
</nav>