config/routes.rb
Rails.application.routes.draw do
  resources :announcements
  devise_for :users
  resources :proposals
  resources :reviews
  resources :comments

  root :to => 'landing_page#index'
  post '/' => 'landing_page#index', as:'home_page'
  get '/edit' => 'users#edit_profile', as: 'edit_profile'
  patch '/edit/:id' => 'users#edited_profile', as: 'user'
  get '/proposals' => 'proposals#index', as:'proposals_page'
  get '/proposals/:id/veto' => 'proposals#veto', as: 'veto'
  post '/proposals/:id/veto' => 'proposals#vetoed', as: 'vetoed'
  get '/proposals/:id/assign' => 'proposals#assign', as: 'assign_proposal'
  post '/proposals/:id/assignhead/:memberid' => 'proposals#assign_head_to_proposal', as: 'assign_head_to_proposal'
  post '/proposals/:id/assignmember/:memberid' => 'proposals#assign_member_to_proposal', as: 'assign_member_to_proposal'
  post '/proposals/:id/removehead/:memberid' => 'proposals#remove_head_from_proposal', as: 'remove_head_from_proposal'
  post '/proposals/:id/removemember/:memberid' => 'proposals#remove_member_from_proposal', as: 'remove_member_from_proposal'
  get '/proposals/:id/editsubmissionperiod' => 'proposals#edit_submission_period', as: 'edit_submission_period'
  post '/proposals/:id/editsubmissionperiod' => 'proposals#edit_period', as: 'edit_period'
  get '/under_construction', to: "landing_page#under_construction", as: "under_construction"
  get '/proposals/:id/withdraw' => 'proposals#withdraw', as: 'withdraw_proposal'
  get 'proposals/:id/reviews' => 'reviews#index', as: 'reviews_page'
  post 'proposals/:id/reviews' => 'reviews#add_comment', as:"add_comment"
  post 'proposals/:id/uphold' => 'proposals#uphold', as:"uphold"
  get '/assign' => 'users#index', as: 'assign_account'
  get '/user/:id' => 'users#view', as: 'view_user'
  get '/remove/:id' => 'users#edit', as: 'edit_account'
  post '/add/:id/researcher' => 'users#add_researcher', as: 'add_researcher'
  post '/add/:id/dean' => 'users#add_dean', as: 'add_dean'
  post '/add/:id/member' => 'users#add_committee_member', as: 'add_committee_member'
  post '/add/:id/head' => 'users#add_committee_head', as: 'add_committee_head'
  post '/add/:id/admin' => 'users#add_admin', as: 'add_admin'

  post '/remove/:id/researcher' => 'users#remove_researcher', as: 'remove_researcher'
  post '/remove/:id/dean' => 'users#remove_dean', as: 'remove_dean'
  post '/remove/:id/member' => 'users#remove_committee_member', as: 'remove_committee_member'
  post '/remove/:id/head' => 'users#remove_committee_head', as: 'remove_committee_head'
  post '/remove/:id/admin' => 'users#remove_admin', as: 'remove_admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/proposal.rb
class Proposal < ApplicationRecord
	validates :title, presence: true
	validates :researcher, presence: true
	validates :descriptions, presence: true
	validates :avatar, presence: true

	belongs_to :researcher, optional: true
	after_initialize :set_defaults
	after_initialize :set_status
	has_one :submission_period, dependent: :destroy
	has_many :reviews, dependent: :destroy
	has_many :committee_members, through: :reviews
	has_many :committee_heads, through: :reviews
	has_many :comments

	mount_uploader :avatar, AvatarUploader
	def set_defaults
	    self.title  ||= ''
	    self.researcher_name ||= ''
	    # self.coresearchers ||= ''
	    self.objectives ||= ''
	    self.status ||= -1
	    # self.votes ||= 0
	    # self.is_vetoed = false if self.is_vetoed.nil?
	    self.is_withdrawn = false if self.is_decided.nil?
	 	self.is_decided = false if self.is_decided.nil?
	 	self.is_assigned_reviewers = true if self.reviews.length == 3
	 	self.is_submitted = false if self.is_submitted.nil?
	 	self.create_submission_period!(proposal_id: self.id) if self.submission_period.nil?
	 	self.is_submitted = self.avatar.nil? ? false : true
	 end

	 def set_status
	 	if self.is_withdrawn
 			self.status = -2
 		elsif self.is_assigned_reviewers == false
	 		self.status = -1
	 	elsif !self.submission_period.is_set
	 		self.status = 0
	 	elsif self.submission_period.is_active_votation and self.submission_period.is_set and !self.is_decided
	 		self.status = 1
	 	end
	 	self.is_decided = true if self.status > 1
	 end

	 def status_string
	 	status
	 	if self.status == -2
	 		status = "Proposal withdrawn"
	 	elsif self.status == -1
	 		status = "Reviewers have not yet been assigned"
	 	elsif self.status == 0
	 		status = "Not under votation period"
	 	elsif self.status = 1
	 		status = "Under votation period"
	 	elsif self.status == 2
	 		status = "Accepted"
	 	elsif self.status = 3
	 		status = "Rejected"
	 	else
	 		status = "Unknown"
	 	end
	 	return status
	 end	
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
	include ActionView::Helpers::NumberHelper
	def new
		@proposal = Proposal.new
		authorize! :new, @proposal
	end

	def create
		@proposal = Proposal.new(proposal_params)
		authorize! :create, @proposal
		@proposal.researcher_id = current_user.id

		if @proposal.save
			redirect_to proposals_page_path
		end
	end

	def index
		authorize! :index, Proposal
		@proposals = []
		if current_user
			if current_user.curr_type == 'CommitteeMember'
				@proposals += current_user.committee_member.proposals
			elsif current_user.curr_type == 'CommitteeHead'
				@proposals += current_user.committee_head.proposals
			else
				@proposals = Proposal.accessible_by(current_ability).order('id DESC')
			end
		end

	end

	def show
		@proposal = Proposal.find(params[:id])
		authorize! :read, @proposal

	end

	def edit
		@proposal = Proposal.find(params[:id])
		authorize! :edit, @proposal
	end

	def update
		@proposal = Proposal.find(params[:id])
		authorize! :update, @proposal
		if @proposal.update(proposal_params)
			redirect_to proposals_page_path
		else
			render 'edit'
		end
	end

	def destroy
		@proposal = Proposal.find(params[:id])
		authorize! :destroy, @proposal
    	@proposal.destroy
    	redirect_to proposals_page_path
	end

	def withdraw
		@proposal = Proposal.find(params[:id])
		@proposal.is_withdrawn = true
		@proposal.save!
		redirect_to proposals_page_path
	end

	def veto
		@proposal = Proposal.find(params[:id])
		@reviews = @proposal.reviews
		authorize! :veto, @proposal
		@reviews.each do |review|
			if review.committee_member_id.nil?
				@headreview = review
			end
		end
		@proposal.save!
	end

	def vetoed
		@proposal = Proposal.find(params[:id])
		s = "/proposals/"
		s << params[:id].to_s
		s << "/veto"
		if params[s][:vote] == '0'
			@proposal.submission_period.is_set = false
		else
			@proposal.status = params[s][:vote]
			@proposal.is_decided = true
		end
		@proposal.submission_period.save!
		@proposal.save!
	end

	def uphold
		@proposal = Proposal.find(params[:id])
		@reviews = @proposal.reviews
		@reviews.each do |review|
			if review.committee_member_id.nil?
				if review.vote == 0
					@proposal.submission_period.is_set = false
				else
					@proposal.status = review.vote
					@proposal.is_decided = true
				end
			end
		end
		@proposal.submission_period.save!
		@proposal.save!

		redirect_to reviews_page_path
	end

	def assign
		@proposal = Proposal.find(params[:id])
		authorize! :assign, @proposal
		@heads = []
		@reviewers = []
		committee_heads = CommitteeHead.where(activated: true)
		committee_members = CommitteeMember.where(activated: true)
		if !committee_heads.empty?
			committee_heads.each do |committee_head|
				if committee_head.proposals.include? @proposal
					@heads.append(committee_head)
				end
			end
		end

		if !committee_members.empty?
			committee_members.each do |committee_member|
				if committee_member.proposals.include? @proposal
					@reviewers.append(committee_member)
				end
			end
		end
		if @heads
			@possible_heads = committee_heads - @heads
		else
			@possible_heads = committee_heads
		end

		if @reviewers
			@possible_reviewers = committee_members - @reviewers
		else
			@possible_reviewers = committee_members
		end
	end

	def assign_head_to_proposal
		@proposal = Proposal.find(params[:proposalid])
		authorize! :assign, @proposal
		@reviewer = CommitteeHead.find(params[:memberid])
		review = Review.where('proposal_id = ? and committee_head = ?', @proposal.id, @reviewer.id)
		@reviewer.proposals.append(@proposal)
		if @proposal.committee_members.length == 2 and @proposal.committee_heads.length == 1
			@proposal.is_assigned_reviewers = true
		end
		@proposal.save!
		redirect_to assign_proposal_path
	end

	def assign_member_to_proposal
		@proposal = Proposal.find(params[:proposalid])
		authorize! :assign, @proposal
		@reviewer = CommitteeMember.find(params[:memberid])
		@reviewer.proposals.append(@proposal)
		if @proposal.committee_members.length == 2 and @proposal.committee_heads.length == 1
			@proposal.is_assigned_reviewers = true
		end
		@proposal.save!
		redirect_to assign_proposal_path
	end

	def remove_head_from_proposal
		@proposal = Proposal.find(params[:proposalid])
		authorize! :assign, @proposal
		@reviewer = CommitteeHead.find(params[:memberid])
		@reviewer.proposals.delete(@proposal)
		if @proposal.committee_members.length != 2 or @proposal.committee_heads.length != 1
			@proposal.is_assigned_reviewers = false
		end
		@proposal.save!
		redirect_to assign_proposal_path
	end

	def remove_member_from_proposal
		@proposal = Proposal.find(params[:proposalid])
		authorize! :assign, Proposal
		@reviewer = CommitteeMember.find(params[:memberid])
		@reviewer.proposals.delete(@proposal)
		if @proposal.committee_members.length != 2 or @proposal.committee_heads.length != 1
			@proposal.is_assigned_reviewers = false
		end
		@reviewer.save!
		@proposal.save!
		redirect_to assign_proposal_path
	end

	def edit_submission_period
		@proposal = Proposal.find(params[:id])
		authorize! :edit, SubmissionPeriod
	end

	def edit_period
		@proposal = Proposal.find(params[:id])
		@proposal.submission_period.is_set = true
		s = "/proposals/"
		s << params[:id].to_s
		s << "/editsubmissionperiod"
		@proposal.submission_period.start_votation = params[s][:start]
		@proposal.submission_period.end_votation = params[s][:deadline]
		@proposal.submission_period.save!
		@proposal.save!


		redirect_to proposals_page_path
	end

	def update_submission_period
		@proposal = Proposal.find(params[:id])
		authorize! :update, @proposal
		if @proposal.update_submission_period(proposal_params)
			redirect_to proposals_page_path
		else
			render 'edit_submission_period'
		end
	end

	private def proposal_params
     	params.require(:proposal).permit(:title, :objectives, :descriptions, :researcher_name, :avatar)
    end

    private def submission_period_params
     	params.require(:proposal).permit(:title, :researcher_name, :avatar)
    end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/assign.html.erb
<h1>Assign Committee</h1>
<table class="ui celled padded table">
	<tbody>
		<tr><th>Title</th><td><%= @proposal.title %></td></tr>
		<tr><th>Researcher</th><td><%= User.find(id = @proposal.researcher.user_id).full_name %></td></tr>
		<tr><th>Objectives</th><td><%= @proposal.objectives %></td></tr>
		<tr><th>Description</th><td><%= @proposal.descriptions %></td></tr>
		<tr><th>File Information</th><td><%= File.basename(@proposal.avatar.path) %> (<%= number_to_human_size(File.size(@proposal.avatar.path)) %>), uploaded <%= File.mtime(@proposal.avatar.path) %></td></tr>
		<tr><th>Status</th><td><%= @proposal.status_string %></td></tr>
	</tbody>
</table>

<table class="table">
	<thead>
		<th>Eligible Committee Heads:</th>
		<th colspan="1"></th>
	</thead>
	<% if @heads %>
		<% @heads.each do |head| %>
			<tr>
				<td><%= User.find(head.id).full_name %> (Current)</td>
				<td><%= link_to "Remove from Proposal", remove_head_from_proposal_path(:proposalid => @proposal.id,:memberid => head.id), :method => :post %></td>
			</tr>
		<% end %>
	<% end %>
	<% if @possible_heads %>
		<% @possible_heads.each do |possible_head| %>
			<tr>
				<td><%= User.find(possible_head.user_id).full_name %></td>
				<td><%= link_to "Assign to Proposal", assign_head_to_proposal_path(:proposalid => @proposal.id,:memberid => possible_head.id), :method => :post %></td>
			</tr>
		<% end %>
	<% end %>
</table>

<table class="table">
	<thead>
		<th>Eligible Reviewers:</th>
		<th colspan="1"></th>
	</thead>
	<% if @reviewers %>
		<% @reviewers.each do |reviewer| %>
			<tr>
				<td><%= User.find(reviewer.id).full_name %> (Current)</td>
				<td><%= link_to "Remove from Proposal", remove_member_from_proposal_path(:proposalid => @proposal.id,:memberid => reviewer.id), :method => :post %></td>
			</tr>
		<% end %>
	<% end %>
	<% if @possible_reviewers %>
		<% @possible_reviewers.each do |possible_reviewer| %>
			<tr>
				<td><%= User.find(possible_reviewer.user_id).full_name %></td>
				<td><%= link_to "Assign to Proposal", assign_member_to_proposal_path(:proposalid => @proposal.id,:memberid => possible_reviewer.id), :method => :post %></td>
			</tr>
		<% end %>
	<% end %>
</table>

<%= link_to 'Back', proposals_page_path, :class => "ui primary button" %>

app/views/proposals/create.html.erb
<h1>Create</h1>

app/views/proposals/delete.html.erb
<h1>Delete</h1>

app/views/proposals/edit.html.erb
<h1>Edit Proposal</h1>

<%= form_for @proposal, html: { multipart: true, class: "ui form" } do |f| %>
<div class="ui padded segment">
  <div class="required field">
    <label>Title</label>
    <%= f.text_field :title , autofocus: true, required: true %>
  </div>
  <div class="required field">
    <label>Objectives</label>
    <%= f.text_area :objectives, required: true %>
  </div>
  <div class="required field">
    <label>Description</label>
    <%= f.text_area :descriptions, required: true %>
  </div>
  <% if @proposal.avatar_url %>
    <label>Current File: <%= image_tag("pdf-file.png", :width => 16) %> <%= File.basename(@proposal.avatar.path) %> </label>
    <%= link_to "View", @proposal.avatar_url, target: :_blank %>
  <% end %>
  <div class="field">
    <label>Change File (optional)</label>
    <%= f.file_field :avatar, accept: '.pdf', required: false %>
  </div>
</div>
  <%= f.submit "Save", :class => "ui primary button" %>
  <%= link_to 'Cancel', proposals_path, :class => "ui primary button" %>
<% end %>

app/views/proposals/edit_submission_period.html.erb
<% if can? :edit, SubmissionPeriod %>
  <h1>Set Submission Period</h1>
  <%= form_for edit_period_path, :html => {:class => "ui form"}, :method => :post do |f|%>
    <div class="ui padded segment">
      <div class="field">
        <label>Enter start of votation:</label>
        <%= f.datetime_field :start, required: true%><br>
      </div>
      <div class="field">
        <label>Enter deadline of votation:</label>
        <%= f.datetime_field :deadline, required: true%><br>
      </div>
    </div>
      <%= f.submit "Submit", :class => "ui primary button" %>
      <%= link_to 'Cancel', proposals_path, :class => "ui primary button" %>
  <% end %>
<% end %>

app/views/proposals/index.html.erb
<h1>Proposals</h1>

<% if can? :create, Proposal %>
    <%= link_to "New Proposal", new_proposal_path, :class => "ui primary button" %>
<% end %>

<div class="ui segments">
  <div class="ui segment">
    <div class="ui divided items">
      <% @proposals.each do |proposal| %>
        <div class="item">
          <div class="content">
            <% if can? :read, proposal %>
          	  <%= link_to proposal.title, proposal_url(proposal.id), :class => "header" %>
          	<% else %>
          		<h1 class="ui medium header"><%= proposal.title %></hi>
          	<% end %>
            <div class="extra">
              <div class="ui label">
                <%= proposal.status_string %>
              </div>
              <% if can? :destroy, proposal %>
                <%= link_to "Delete", proposal, method: :delete, data: { confirm: 'Deleting Proposal: Are you sure?'}, :class => "ui right floated primary button" %>
              <% end %>
              <% if can? :withdraw, proposal %>
                <% if !proposal.is_withdrawn and !proposal.is_decided %>
                  <%= link_to "Withdraw", withdraw_proposal_path(proposal.id), data: { confirm: 'Withdrawing Proposal: Are you sure?'}, :class => "ui right floated primary button" %>
                <%# else %>
                  <%#= link_to "Submit", submit_proposal_path(proposal.id), :class => "ui right floated primary button" %>
                <% end %>
              <% end %>
              <% if can? :update, proposal %>
                <%= link_to "Update", edit_proposal_path(proposal.id), :class => "ui right floated primary button" %>
            	<% end %>
              <% if can? :review, proposal %>
                <%= link_to "See reviews", reviews_page_path(proposal.id), :class => "ui right floated primary button" %>
              <% end %>
              <% if can? :assign, proposal %>
                <% if proposal.is_assigned_reviewers %>
                  <div class="ui label">Assigned</div>
                <% else %>
                  <div class="ui label">Not Yet Assigned</div>
                <% end %>
                <% if proposal.is_assigned_reviewers %>
                  <%= link_to "Reassign", assign_proposal_path(proposal.id), :class => "ui right floated primary button" %>
                <% else %>
                  <%= link_to "Assign", assign_proposal_path(proposal.id), :class => "ui right floated primary button" %>
                <% end %>
              <% end %>
              <% if can? :review, proposal %>
                <% if proposal.submission_period.is_set == false and !proposal.is_withdrawn%>
                  <% if can? :update, proposal.submission_period %>
                    <%= link_to "Set proposal timeline", edit_submission_period_path(proposal.id), :class => "ui right floated primary button" %>
                  <% end %>
                <% else %>
                  <% if can? :update, proposal.submission_period and !proposal.is_withdrawn%>
                    <%= link_to "Update proposal timeline", edit_submission_period_path(proposal.id), :class => "ui right floated primary button" %>
                  <% end %>
                  <% if current_user.curr_type == 'CommitteeMember' %>
                    <% if !Review.find_by('committee_member_id = ? AND proposal_id = ?', current_user.committee_member.id, proposal.id).is_decided %>
                      <div class="ui label">Not yet voted</div>
                    <% else %>
                      <div class="ui label">Voted</div>
                    <% end %>
                  <% elsif current_user.curr_type == 'CommitteeHead' %>
                    <% if !Review.find_by('committee_head_id = ? AND proposal_id = ?', current_user.committee_head.id, proposal.id).is_decided %>
                      <div class="ui label">Not yet voted</div>
                    <% else %>
                      <div class="ui label">Voted</div>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/proposals/new.html.erb
<h1>New Proposal</h1>

<%= form_for @proposal, html: { multipart: true, class: "ui form" } do |f| %>
  <div class="ui padded segment">
    <div class="required field">
      <label>Title</label>
      <%= f.text_field :title , autofocus: true, required: true %>
    </div>
    <div class="required field">
      <label>Objectives</label>
      <%= f.text_area :objectives, required: true %>
    </div>
    <div class="required field">
      <label>Description</label>
      <%= f.text_area :descriptions, required: true %>
    </div>
    <div class="required field">
      <label>File</label>
      <%= f.file_field :avatar, accept: '.pdf', required: true %>
    </div>
  </div>
  <%= f.submit "Save", :class => "ui primary button" %>
  <%= link_to 'Back', proposals_path, :class => "ui primary button" %>
<% end %>

app/views/proposals/show.html.erb
<h1>Proposal Details</h1>
<table class="ui celled padded table">
	<tbody>
		<tr><th>Title</th><td><%= @proposal.title %></td></tr>
		<tr><th>Researcher</th><td><%= User.find(id = @proposal.researcher.user_id).full_name %></td></tr>
		<tr><th>Objectives</th><td><%= @proposal.objectives %></td></tr>
		<tr><th>Description</th><td><%= @proposal.descriptions %></td></tr>
		<tr><th>File Information</th><td><%= File.basename(@proposal.avatar.path) %> (<%= number_to_human_size(File.size(@proposal.avatar.path)) %>), uploaded <%= File.mtime(@proposal.avatar.path) %></td></tr>
		<tr><th>Status</th><td><%= @proposal.status_string %></td></tr>
	</tbody>
</table>
<br>
<% if can? :read, @proposal %>
	<td>
		<% if @proposal.avatar_url %>
			<%= link_to "Download proposal", @proposal.avatar_url, :class => "ui primary button" %>
		<% end %>
	</td>
<% end %>
<% if can? :update, @proposal %>
<% if (@proposal.submission_period.is_active_votation == false) %>
	<%= link_to 'Edit', edit_proposal_path(@proposal), :class => "ui primary button" %>
<% end %>
<% end %>
<% if can? :review, @proposal %>
	<%= link_to "See Reviews", reviews_page_path(@proposal.id), :class => "ui primary button"%>
<% end %>
<%= link_to 'Back', proposals_path, :class => "ui primary button" %>

app/views/proposals/veto.html.erb
<% if can? :veto, @proposal %>
  <h1> Vetoing: <%= @proposal.title %> </h1>
  <%= form_for vetoed_path, :html => {:class => "ui form"}, :remote => "true", :method => :post do |f| %>
    <div class="ui padded segment">
      <% if @headreview.vote != 2 %>
      	<%= f.radio_button :vote,'2'%>
      	<%= f.label :vote, 'Accept'%>
      	<br>
      <%end%>
      <% if @headreview.vote != 3 %>
  	    <%= f.radio_button :vote,'3'%>
  	    <%= f.label :vote, 'Reject'%>
  	    <br>
      <%end%>
      <% if @headreview.vote != 0 %>
  	    <%= f.radio_button :vote,'0'%>
  	    <%= f.label :vote, 'Resubmit'%>
      <%end%>
    </div>
    <br>
    <%= f.submit "Save", :class => "ui primary button", :onclick => "modalVeto()" %>
  <% end %>
<% end %>

<div class="ui modal" style="height: 180px;">
  <div class="header">Proposal Status Confirmed</div>
  <div class="content">
    <p> Committee decision vetoed:
      <%= @proposal.status_string %>
    </p>
  </div>
  <div class="actions">
    <%= link_to "OK", reviews_page_path, :class => "ui button" %>
  </div>
</div>

<script language="javascript">
  function modalVeto(){
    $('.ui.modal').modal('show');
  }
</script>