config/routes.rb
Rails.application.routes.draw do
  resources :announcements
  devise_for :users
  resources :proposals
  resources :reviews
  resources :comments

  root :to => 'landing_page#index'
  post '/' => 'landing_page#index', as:'home_page'
  get '/edit' => 'users#edit_profile', as: 'edit_profile'
  patch '/edit/:id' => 'users#edited_profile', as: 'user'
  get '/proposals' => 'proposals#index', as:'proposals_page'
  get '/proposals/:id/veto' => 'proposals#veto', as: 'veto'
  post '/proposals/:id/veto' => 'proposals#vetoed', as: 'vetoed'
  get '/proposals/:id/assign' => 'proposals#assign', as: 'assign_proposal'
  post '/proposals/:id/assignhead/:memberid' => 'proposals#assign_head_to_proposal', as: 'assign_head_to_proposal'
  post '/proposals/:id/assignmember/:memberid' => 'proposals#assign_member_to_proposal', as: 'assign_member_to_proposal'
  post '/proposals/:id/removehead/:memberid' => 'proposals#remove_head_from_proposal', as: 'remove_head_from_proposal'
  post '/proposals/:id/removemember/:memberid' => 'proposals#remove_member_from_proposal', as: 'remove_member_from_proposal'
  get '/proposals/:id/editsubmissionperiod' => 'proposals#edit_submission_period', as: 'edit_submission_period'
  post '/proposals/:id/editsubmissionperiod' => 'proposals#edit_period', as: 'edit_period'
  get '/under_construction', to: "landing_page#under_construction", as: "under_construction"
  get '/proposals/:id/withdraw' => 'proposals#withdraw', as: 'withdraw_proposal'
  get 'proposals/:id/reviews' => 'reviews#index', as: 'reviews_page'
  post 'proposals/:id/reviews' => 'reviews#add_comment', as:"add_comment"
  post 'proposals/:id/uphold' => 'proposals#uphold', as:"uphold"
  get '/assign' => 'users#index', as: 'assign_account'
  get '/user/:id' => 'users#view', as: 'view_user'
  get '/remove/:id' => 'users#edit', as: 'edit_account'
  post '/add/:id/researcher' => 'users#add_researcher', as: 'add_researcher'
  post '/add/:id/dean' => 'users#add_dean', as: 'add_dean'
  post '/add/:id/member' => 'users#add_committee_member', as: 'add_committee_member'
  post '/add/:id/head' => 'users#add_committee_head', as: 'add_committee_head'
  post '/add/:id/admin' => 'users#add_admin', as: 'add_admin'

  post '/remove/:id/researcher' => 'users#remove_researcher', as: 'remove_researcher'
  post '/remove/:id/dean' => 'users#remove_dean', as: 'remove_dean'
  post '/remove/:id/member' => 'users#remove_committee_member', as: 'remove_committee_member'
  post '/remove/:id/head' => 'users#remove_committee_head', as: 'remove_committee_head'
  post '/remove/:id/admin' => 'users#remove_admin', as: 'remove_admin'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def index
		@proposal = Proposal.find(params[:id])
		@comment = Comment.new
		@comment.proposal_id = @proposal.id
		@reviews = @proposal.reviews
		puts "+++++++++"
		puts @reviews.length
		puts "+++++++++"
		authorize! :index, Review
		@my_review = nil
		if current_user.curr_type == 'CommitteeMember'
			@my_review = Review.where(proposal_id: @proposal).where(committee_member_id: current_user.committee_member.id).take
		elsif current_user.curr_type == 'CommitteeHead'
			@my_review = Review.where(proposal_id: @proposal).where(committee_head_id: current_user.committee_head.id).take
		else
			@my_review = nil
		end

		@canvote = false
		if(@proposal.submission_period.end_votation) and (@proposal.submission_period.start_votation)
			if (Time.now < @proposal.submission_period.end_votation) and (Time.now > @proposal.submission_period.start_votation)
				@canvote = true
			end
		end
	end

	def new
		authorize! :new, Review
		@proposal = Proposal.find(params[:id])
		@review = Review.new
		session[:passed_variable] = @proposal.id
	end

	def create
		authorize! :create, Review
		@review = Review.new(review_params)
		@review.proposal_id = session[:passed_variable]
		if current_user.curr_type == 'CommitteeMember'
			@review.committee_member_id = current_user.committee_member.id
		elsif current_user.curr_type == 'CommitteeHead'
			@review.committee_head_id = current_user.committee_head.id
		end
		if @review.save
			redirect_to reviews_page_path(session[:passed_variable])
		end
	end

	def edit
		@review = Review.find(params[:reviewid])
		authorize! :edit, @review
		@proposal = Proposal.find(params[:proposalid])
		session[:proposal] = @proposal.id
		# session[:passed_variable2] = @review.id
	end

	def update
		# num =  session[:passed_variable2]
		# @review = Review.find(num)
		@review = Review.find(params[:id])
		authorize! :update, @review
		if @review.update(review_params)
			@review.is_decided = true
			@review.save!
			# redirect_to reviews_page_path(session[:passed_variable])
			redirect_to reviews_page_path(session[:proposal])
		else
			render 'edit'
		end
	end

	def add_comment
		@proposal = Proposal.find(params[:id])
		s = "/proposals/"
		s << params[:id].to_s
		s << "/reviews"
		puts '|',params,'|'
		puts '+',@proposal,'+'
		if current_user.curr_type == 'Dean'
			@proposal.comments.create!(comment: params[:content], dean_id: current_user.dean.id)
		elsif current_user.curr_type == 'CommitteeMember'
			@proposal.comments.create!(comment: params[:content], committee_member_id: current_user.committee_member.id)
		else current_user.curr_type == 'CommitteeHead'
			@proposal.comments.create!(comment: params[:content], committee_head_id: current_user.committee_head.id)
		end

		# @proposal.comments.save!
		@proposal.save!

		redirect_to reviews_page_path
	end

	

	private

	def review_params
      params.require(:review).permit(:vote)
	end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/edit.html.erb
<h1> Review for <%= @proposal.title %> </h1>
<%= form_for @review, :html => {:class => "ui form"} do |f| %>
  <div class="ui padded segment">
    <%= f.radio_button :vote,'2'%>
    <%= f.label :vote, 'Accept'%>
    <br>
    <%= f.radio_button :vote,'3'%>
    <%= f.label :vote, 'Reject'%>
    <br>
    <%= f.radio_button :vote,'0'%>
    <%= f.label :vote, 'Resubmit'%>
  </div>
  <br>
  <%= f.submit "Save", :class => "ui primary button" %>
<% end %>

app/views/reviews/index.html.erb
<h1>Review Proposal</h1>
<table class="ui celled padded table">
	<tbody>
		<tr><th>Title</th><td><%= @proposal.title %></td></tr>
		<tr><th>Researcher</th><td><%= User.find(id = @proposal.researcher.user_id).full_name %></td></tr>
		<tr><th>Objectives</th><td><%= @proposal.objectives %></td></tr>
		<tr><th>Description</th><td><%= @proposal.descriptions %></td></tr>
		<tr><th>File Information</th><td><%= File.basename(@proposal.avatar.path) %> (<%= number_to_human_size(File.size(@proposal.avatar.path)) %>), uploaded <%= File.mtime(@proposal.avatar.path) %></td></tr>
		<tr><th>Status</th><td><%= @proposal.status_string %></td></tr>
	</tbody>
</table>
<br>
<% if @proposal.avatar_url %>
    <%= link_to "Download proposal", @proposal.avatar_url, :class => "ui primary button" %>
<% end %>
<% if can? :update, @my_review %>
    <% if @canvote and !@proposal.is_withdrawn %>
        <% if @my_review.is_decided %>
            <%= link_to "Update my review", edit_review_path(:reviewid=>@my_review.id, :proposalid=>@proposal.id), :class => "ui primary button" %>
        <% else %>
            <%= link_to "Review", edit_review_path(:reviewid=>@my_review.id, :proposalid=>@proposal.id), :class => "ui primary button" %>
        <% end %>
    <% else %> Voting is closed
    <% end %>
<% end %>
<table class = "table">
<thead><h2>Reviews</h2></thead>
<%#= link_to "New review", new_review_path(:id=>@proposal.id), :class => "ui primary button" %>
<% @count = 0 %>
<% @reviews.each do |review| %>
      <tr>
        <td>
            <% if review.is_decided %>
                <% if review.vote == 2 %>
                    Accept
                <% elsif review.vote == 3 %>
                    Reject
                <% elsif review.vote == 0 %>
                    Resubmit
                <% end %>
                <% @count = @count + 1 %>
            <% end %>
        </td>
        <td>
            <% if !review.is_decided %>
                Not yet voted
            <% else %>
                Voted
            <% end %>
        </td>
        <td>
        	<% if !review.committee_member_id.nil? %>
        		<%= User.find(id = review.committee_member.user_id).full_name %>
        	<% else %>
        		<%= User.find(id = review.committee_head.user_id).full_name %>
        	<% end %>
        </td>
      </tr>
<% end %>
</table>
<% if can? :comment, @proposal %>
    <h2>Comments</h2>
    <% @proposal.comments.each do |comment| %>
        <% if comment.dean_id.nil? and comment.committee_member_id.nil? %>
            <% @head = CommitteeHead.find(comment.committee_head_id) %>
            <% @user =  User.find(@head.user_id) %>
            <b>
                <%= @user.full_name %>
            </b>
        <% elsif comment.committee_head_id.nil? and comment.committee_member_id.nil? %>
            <% @head = Dean.find(comment.dean_id) %>
            <% @user =  User.find(@head.user_id) %>
            <b>
                <%= @user.full_name %>
            </b>
        <% else %>
            <% @head = CommitteeMember.find(comment.committee_member_id) %>
            <% @user =  User.find(@head.user_id) %>
            <b>
                <%= @user.full_name %>
            </b>
        <%end%>
        :
        <%= comment.comment %>
        <br>
    <% end %>
<% end %>

<% if can? :comment, @proposal %>
    <h2> Add new comment </h2>
    <%= form_for add_comment_path, :method => :post do |f| %>
        <div class="field">
            <div class="ui icon input">
                <input type="text" name="content" placeholder="Comment">
            </div>
        </div>
        <input type="submit" style="position: absolute; left: -9999px; width: 1px; height: 1px;" tabindex="-1" />
    <% end %>
<% end %>

<br>
<% if can? :veto, @proposal %>
<% if @count == 3 and @proposal.submission_period.is_active_votation and @proposal.is_decided != true%>
    <%= link_to "Uphold", uphold_path(@proposal.id), :class => "ui primary button", :onclick => "modalUphold()", :method => :post %>
    <%= link_to "Veto", veto_path(@proposal.id), :class => "ui primary button" %>
<% end %>
<% end %>
<%= link_to 'Back', proposals_path, :class => "ui primary button" %>

<div class="ui modal" style="height: 180px;">
  <div class="header">Proposal Status Confirmed</div>
  <div class="content">
    <p> Committee decision upheld:
      <%= @proposal.status_string %>
    </p>
  </div>
  <div class="actions">
    <%= link_to "OK", reviews_page_path, :class => "ui button" %>
  </div>
</div>

<script language="javascript">
  function modalUphold(){
    $('.ui.modal').modal('show');
  }
</script>

app/views/reviews/new.html.erb
<h1> Review for <%= @proposal.title %> </h1>
<%= form_for @review, :html => {:class => "ui form"} do |f| %>
  <div class="ui padded segment">
    <%= f.radio_button :vote,'2'%>
    <%= f.label :vote, 'Accept'%>
    <br>
    <%= f.radio_button :vote,'3'%>
    <%= f.label :vote, 'Reject'%>
    <br>
    <%= f.radio_button :vote,'0'%>
    <%= f.label :vote, 'Resubmit'%>
  </div>
  <br>
  <%= f.submit "Save", :class => "ui primary button" %>
<% end %>